# Generated by Django 5.0 on 2025-11-09 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=100, unique=True)),
                ('cliente_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalles', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('creada', 'Creada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta Pendiente',
                'verbose_name_plural': 'Ventas Pendientes',
                'db_table': 'pending_sale',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_note',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetailNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.salesnote')),
            ],
            options={
                'db_table': 'detail_note',
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=50)),
                ('estado', models.CharField(default='completado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.salesnote')),
            ],
            options={
                'db_table': 'cash_payment',
            },
        ),
    ]
