# Generated by Django 5.0 on 2025-11-09 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesnote',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
