# Generated by Django 5.0 on 2025-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=100, unique=True)),
                ('cliente_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('tipo_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalles', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('creada', 'Creada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta Pendiente',
                'verbose_name_plural': 'Ventas Pendientes',
                'db_table': 'pending_sale',
                'ordering': ['-created_at'],
            },
        ),
    ]
