# Generated by Django 5.0 on 2025-10-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'category',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'provider',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.provider')),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedores',
                'db_table': 'provider_product',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', through='productos.ProviderProduct', to='productos.provider'),
        ),
    ]
