# Generated by Django 5.0 on 2025-10-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_cuotas', models.PositiveIntegerField(default=3)),
                ('dias_entre_cuotas', models.PositiveIntegerField(default=10)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Crédito',
                'verbose_name_plural': 'Configuraciones de Crédito',
                'db_table': 'credit_config',
            },
        ),
        migrations.CreateModel(
            name='CreditInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('cuota', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Cuota de Crédito',
                'verbose_name_plural': 'Cuotas de Crédito',
                'db_table': 'credit_installment',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=50)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='completado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='creditos.creditinstallment')),
            ],
            options={
                'verbose_name': 'Pago de Crédito',
                'verbose_name_plural': 'Pagos de Crédito',
                'db_table': 'credit_payment',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_intereses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_aplicada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='activo', max_length=20)),
                ('fecha_inicial', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='ventas.salesnote')),
            ],
            options={
                'verbose_name': 'Venta a Crédito',
                'verbose_name_plural': 'Ventas a Crédito',
                'db_table': 'credit_sale',
                'ordering': ['-fecha_inicial'],
            },
        ),
        migrations.AddField(
            model_name='creditinstallment',
            name='venta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='creditos.creditsale'),
        ),
    ]
