# Generated by Django 5.0 on 2025-11-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='nota_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='ventas.salesnote'),
        ),
        migrations.AddField(
            model_name='creditinstallment',
            name='venta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='creditos.creditsale'),
        ),
    ]
