# Generated by Django 5.0 on 2025-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditinstallment',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
