# Generated by Django 5.0 on 2025-11-07 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_alter_creditinstallment_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpayment',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
